from sqlalchemy import Column, BigInteger, Numeric, Date, Text, ForeignKey
from app.db.database import Base

class StockOhlcv(Base):
    __tablename__ = 'tb_stock_ohlcv'

    stock_id = Column(BigInteger, ForeignKey('tb_stock_info.id'), primary_key=True)
    ymd = Column(Date, primary_key=True)
    open = Column(Numeric)
    high = Column(Numeric)
    low = Column(Numeric)
    close = Column(Numeric)
    volume = Column(BigInteger)
    ticker = Column(Text, primary_key=True)
    change_rate = Column(Numeric)
    trading_value = Column(Numeric)
    trading_value_institution = Column(Numeric)
    trading_value_other_corporation = Column(Numeric)
    trading_value_individual = Column(Numeric)
    trading_value_foreign = Column(Numeric)
    volume_institution = Column(Numeric)
    volume_other_corporation = Column(Numeric)
    volume_individual = Column(Numeric)
    volume_foreign = Column(Numeric)
    # sma_5 = Column(Numeric)
    # ema_5 = Column(Numeric)
    # sma_20 = Column(Numeric)
    # ema_20 = Column(Numeric)
    # sma_60 = Column(Numeric)
    # ema_60 = Column(Numeric)
    # sma_120 = Column(Numeric)
    # ema_120 = Column(Numeric)
    # sma_240 = Column(Numeric)
    # ema_240 = Column(Numeric)
    # sma_480 = Column(Numeric)
    # ema_480 = Column(Numeric)
    # rsi = Column(Numeric)
    # macd = Column(Numeric)
    # macd_signal = Column(Numeric)
    # macd_hist = Column(Numeric)
    # bb_upper = Column(Numeric)
    # bb_middle = Column(Numeric)
    # bb_lower = Column(Numeric)
    # stoch_k = Column(Numeric)
    # stoch_d = Column(Numeric)
    # obv = Column(Numeric)
    # mfi = Column(Numeric)
    # fib_0 = Column(Numeric)
    # fib_23_6 = Column(Numeric)
    # fib_38_2 = Column(Numeric)
    # fib_50 = Column(Numeric)
    # fib_61_8 = Column(Numeric)
    # fib_100 = Column(Numeric)
    # tenkan_sen = Column(Numeric)
    # kijun_sen = Column(Numeric)
    # senkou_span_a = Column(Numeric)
    # senkou_span_b = Column(Numeric)
    # chikou_span = Column(Numeric)
    # cci = Column(Numeric)
    # vwap = Column(Numeric)
    # atr = Column(Numeric)
    # adx = Column(Numeric)
    # pivot = Column(Numeric)
    # r1 = Column(Numeric)
    # s1 = Column(Numeric)
    # r2 = Column(Numeric)
    # s2 = Column(Numeric)
    # avg_volume_5 = Column(Numeric)
    # avg_trading_value_5 = Column(Numeric) 